# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev25+g5e7a988.d20230528'
__version_tuple__ = version_tuple = (0, 1, 'dev25', 'g5e7a988.d20230528')
